name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:
    inputs:
      release-type:
        description: "Type of release (major, minor, patch, alpha)"
        required: true
        default: alpha
        type: choice
        options:
          - major
          - minor
          - patch
          - alpha

jobs:
  continuous-integration:
    name: "Continuous Integration"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Style
        run: npm run style:check

      - name: Build
        run: npm run build

      - name: Check types
        run: npm run types:check

  continuous-deployment:
      if: github.event_name == 'workflow_dispatch'

      name: 'Continuous Deployment'
      runs-on: ubuntu-latest
      needs: ['continuous-integration']

      steps:
          - uses: actions/checkout@v4
            with: 
              fetch-depth: 0

          - uses: actions/setup-node@v4
            with:
              node-version: '18'

          - name: Install dependencies
            run: npm run install

          - name: Build
            run: npm run build

          - name: Set git configuration 
            run: |
              git config user.name "Animo Solutions"
              git config user.email "development@animo.id"

          - name: Publish
            id: publish
            env:
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

              if [ ${{ inputs.release-type }} == 'alpha' ]; then
                npm run release --preRelease=alpha
              else
                npm run release -i=${{ inputs.release-type }}
              fi
